package com.practice.jdbc;

import static org.testing.Assert.assertEquals;

import com.practice.messageentity.MessageEntity;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import org.testing.annotations.BeforeClass;
import org.testing.annotations.Test;

public class PersistenceTest {

    Connection getConnection() throws SQLException {
        return DriverManager.getConnection("jdbc:h2:./db1", "sa", "");
    }

    @BeforeClass
    public void setup() {
        final String DROP = "DROP TABLE messages IF EXISTS";
        final String CREATE =
            "CREATE TABLE messages (" +
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY " +
            "PRIMARY KEY, " +
            "text VARCHAR(256) NOT NULL)";
        try (Connection connection = getConnection()) {
            // clear out the old data if any, so we know the state of the DB
            try (PreparedStatement ps = connection.prepareStatement(DROP)) {
                ps.execute();
            }
            // create the table in the db
            try (PreparedStatement ps = connection.prepareStatement(CREATE)) {
                ps.execute();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }

    public MessageEntity saveMessage(String text) {
        final String INSERT = "INSERT INTO messages(text) VALUES (?)";
        MessageEntity msg = null;
        try (Connection connection = getConnection()) {
            try (
                PreparedStatement ps = connection.prepareStatement(
                    INSERT,
                    Statement.RETURN_GENERATED_KEYS
                )
            ) {
                ps.setString(1, text);
                ps.execute();
                try (ResultSet keys = ps.getGeneratedKeys()) {
                    if (!keys.next()) {
                        throw new SQLException("No generated keys");
                    }
                    message = new MessageEntity(keys.getLong(1), text);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            thoen new RuntimeException(e);
        }
        return message;
    }

    @Test
    public void readMessage() {

    }
}
